#if DEBUG
import AppKit
import CoreGraphics
import Foundation
import ImageIO
import UniformTypeIdentifiers

/// Procedurally drawn pictures for demo mode: avatars, landscape "photos", a
/// sticker and a voice clip.
///
/// Everything is generated on the spot from a fixed seed — no stock images,
/// no photos of real people, nothing downloaded — so the docs media can be
/// regenerated byte-for-byte-ish on any Mac and can never leak anything.
enum DemoArtwork {

    // MARK: - Deterministic randomness

    /// SplitMix64: tiny, seedable, good enough for brush strokes.
    struct Random {
        private var state: UInt64

        init(seed: UInt64) { state = seed &+ 0x9E37_79B9_7F4A_7C15 }

        mutating func next() -> UInt64 {
            state &+= 0x9E37_79B9_7F4A_7C15
            var z = state
            z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
            z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
            return z ^ (z >> 31)
        }

        /// Uniform in 0..<1.
        mutating func unit() -> CGFloat {
            CGFloat(next() >> 11) / CGFloat(1 << 53)
        }

        mutating func range(_ lower: CGFloat, _ upper: CGFloat) -> CGFloat {
            lower + (upper - lower) * unit()
        }
    }

    // MARK: - Colour helpers

    static func color(_ hex: UInt32, _ alpha: CGFloat = 1) -> CGColor {
        CGColor(
            srgbRed: CGFloat((hex >> 16) & 0xFF) / 255,
            green: CGFloat((hex >> 8) & 0xFF) / 255,
            blue: CGFloat(hex & 0xFF) / 255,
            alpha: alpha)
    }

    private static func gradient(_ stops: [(UInt32, CGFloat)]) -> CGGradient {
        CGGradient(
            colorsSpace: CGColorSpace(name: CGColorSpace.sRGB),
            colors: stops.map { color($0.0) } as CFArray,
            locations: stops.map(\.1))!
    }

    /// One colour fading between two alphas — fog bands.
    private static func fade(_ hex: UInt32, from: CGFloat, to: CGFloat) -> CGGradient {
        CGGradient(
            colorsSpace: CGColorSpace(name: CGColorSpace.sRGB),
            colors: [color(hex, from), color(hex, to)] as CFArray,
            locations: [0, 1])!
    }

    // MARK: - Canvas

    private static func canvas(
        width: Int, height: Int, _ draw: (CGContext, CGSize) -> Void
    ) -> CGImage? {
        guard let context = CGContext(
            data: nil, width: width, height: height, bitsPerComponent: 8, bytesPerRow: 0,
            space: CGColorSpace(name: CGColorSpace.sRGB)!,
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)
        else { return nil }
        context.setShouldAntialias(true)
        context.interpolationQuality = .high
        draw(context, CGSize(width: width, height: height))
        return context.makeImage()
    }

    @discardableResult
    static func writePNG(_ image: CGImage?, to url: URL) -> Bool {
        guard let image,
              let destination = CGImageDestinationCreateWithURL(
                url as CFURL, UTType.png.identifier as CFString, 1, nil)
        else { return false }
        CGImageDestinationAddImage(destination, image, nil)
        return CGImageDestinationFinalize(destination)
    }

    /// Runs AppKit drawing (text, SF Symbols) into a Core Graphics context.
    private static func withAppKit(_ context: CGContext, _ body: () -> Void) {
        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(cgContext: context, flipped: false)
        body()
        NSGraphicsContext.restoreGraphicsState()
    }

    // MARK: - Landscapes

    enum Scene: CaseIterable {
        /// Layered ridges under a dusk sky with a low sun.
        case duskRidge
        /// Pale mountains mirrored in still water.
        case alpineLake
        /// Pine silhouettes fading into fog.
        case forestFog
        /// A star field over a black ridge line.
        case starryNight
        /// Sun rising over a calm sea.
        case seaSunrise
    }

    static func landscape(_ scene: Scene, width: Int, height: Int, seed: UInt64) -> CGImage? {
        canvas(width: width, height: height) { context, size in
            var random = Random(seed: seed)
            switch scene {
            case .duskRidge: drawDuskRidge(context, size, &random)
            case .alpineLake: drawAlpineLake(context, size, &random)
            case .forestFog: drawForestFog(context, size, &random)
            case .starryNight: drawStarryNight(context, size, &random)
            case .seaSunrise: drawSeaSunrise(context, size, &random)
            }
        }
    }

    /// A ridge line as a sum of a few random sines plus fine jitter — reads as
    /// a mountain range rather than as a wave.
    private static func ridge(
        _ size: CGSize, base: CGFloat, amplitude: CGFloat, _ random: inout Random
    ) -> CGPath {
        let path = CGMutablePath()
        path.move(to: CGPoint(x: 0, y: 0))
        let waves = (0..<4).map { index in
            (frequency: random.range(0.6, 2.2) * CGFloat(index + 1),
             phase: random.range(0, .pi * 2),
             weight: amplitude / CGFloat(index + 1))
        }
        let steps = 160
        for step in 0...steps {
            let x = size.width * CGFloat(step) / CGFloat(steps)
            let t = x / size.width
            var y = base
            for wave in waves {
                y += wave.weight * sin(t * .pi * 2 * wave.frequency + wave.phase)
            }
            y += random.range(-amplitude, amplitude) * 0.035
            path.addLine(to: CGPoint(x: x, y: y))
        }
        path.addLine(to: CGPoint(x: size.width, y: 0))
        path.closeSubpath()
        return path
    }

    private static func sky(_ context: CGContext, _ size: CGSize, _ stops: [(UInt32, CGFloat)]) {
        context.drawLinearGradient(
            gradient(stops),
            start: CGPoint(x: 0, y: size.height),
            end: CGPoint(x: 0, y: 0),
            options: [.drawsBeforeStartLocation, .drawsAfterEndLocation])
    }

    private static func glow(
        _ context: CGContext, at center: CGPoint, radius: CGFloat, color hex: UInt32, alpha: CGFloat
    ) {
        let glow = CGGradient(
            colorsSpace: CGColorSpace(name: CGColorSpace.sRGB),
            colors: [color(hex, alpha), color(hex, 0)] as CFArray,
            locations: [0, 1])!
        context.drawRadialGradient(
            glow, startCenter: center, startRadius: 0, endCenter: center, endRadius: radius,
            options: [])
    }

    private static func drawDuskRidge(_ context: CGContext, _ size: CGSize, _ random: inout Random) {
        sky(context, size, [(0x1B1446, 0), (0x51307A, 0.38), (0xC2547A, 0.68), (0xF6A04D, 1)])
        let sun = CGPoint(x: size.width * 0.66, y: size.height * 0.36)
        glow(context, at: sun, radius: size.width * 0.42, color: 0xFFC37A, alpha: 0.55)
        context.setFillColor(color(0xFFE2B0))
        context.fillEllipse(in: CGRect(x: sun.x - size.width * 0.045, y: sun.y - size.width * 0.045,
                                       width: size.width * 0.09, height: size.width * 0.09))
        let layers: [(UInt32, CGFloat, CGFloat)] = [
            (0x8C3F6E, 0.42, 0.10), (0x5E2A5F, 0.33, 0.11), (0x3A1D4A, 0.24, 0.09),
            (0x1E1030, 0.13, 0.07),
        ]
        for (hex, base, amplitude) in layers {
            context.setFillColor(color(hex))
            context.addPath(ridge(size, base: size.height * base,
                                  amplitude: size.height * amplitude, &random))
            context.fillPath()
        }
    }

    private static func drawAlpineLake(_ context: CGContext, _ size: CGSize, _ random: inout Random) {
        let horizon = size.height * 0.42
        sky(context, size, [(0x6FA8DC, 0), (0xA9CDEB, 0.45), (0xE6EEF2, 0.58), (0xE6EEF2, 1)])
        // Mountains, then the same paths flipped into the water, darker.
        let far = ridge(CGSize(width: size.width, height: size.height),
                        base: horizon + size.height * 0.20, amplitude: size.height * 0.14, &random)
        let near = ridge(CGSize(width: size.width, height: size.height),
                         base: horizon + size.height * 0.08, amplitude: size.height * 0.08, &random)
        context.saveGState()
        context.clip(to: CGRect(x: 0, y: horizon, width: size.width, height: size.height - horizon))
        context.setFillColor(color(0x8FA3BF)); context.addPath(far); context.fillPath()
        // Snow line: the top of the far range, lightened.
        context.saveGState()
        context.addPath(far); context.clip()
        context.setFillColor(color(0xF4F7FA, 0.85))
        context.addPath(ridge(size, base: horizon + size.height * 0.30,
                              amplitude: size.height * 0.10, &random))
        context.setBlendMode(.normal)
        context.fill(CGRect(x: 0, y: horizon + size.height * 0.33, width: size.width, height: size.height))
        context.restoreGState()
        context.setFillColor(color(0x3E5A6E)); context.addPath(near); context.fillPath()
        context.restoreGState()

        // Water.
        context.saveGState()
        context.clip(to: CGRect(x: 0, y: 0, width: size.width, height: horizon))
        context.drawLinearGradient(
            gradient([(0x2E5873, 0), (0x5B88A3, 1)]),
            start: CGPoint(x: 0, y: 0), end: CGPoint(x: 0, y: horizon), options: [])
        context.translateBy(x: 0, y: horizon * 2)
        context.scaleBy(x: 1, y: -1)
        context.setFillColor(color(0x7B91A8, 0.55)); context.addPath(far); context.fillPath()
        context.setFillColor(color(0x2C4556, 0.75)); context.addPath(near); context.fillPath()
        context.restoreGState()
        // Ripples.
        for _ in 0..<70 {
            let y = random.range(0, horizon * 0.95)
            let x = random.range(0, size.width)
            let length = random.range(20, 120) * (1 - y / horizon * 0.5)
            context.setFillColor(color(0xFFFFFF, random.range(0.05, 0.16)))
            context.fill(CGRect(x: x, y: y, width: length, height: max(1, size.height * 0.0025)))
        }
    }

    private static func drawForestFog(_ context: CGContext, _ size: CGSize, _ random: inout Random) {
        sky(context, size, [(0xA9B9AE, 0), (0xD3DCD2, 0.6), (0xE9EDE4, 1)])
        let layers: [(UInt32, CGFloat, CGFloat, Int)] = [
            (0x9DB0A2, 0.30, 0.20, 34), (0x6F8A78, 0.18, 0.27, 26),
            (0x3F5A4A, 0.06, 0.36, 18), (0x1F3328, -0.04, 0.50, 11),
        ]
        for (hex, base, height, count) in layers {
            context.setFillColor(color(hex))
            context.fill(CGRect(x: 0, y: 0, width: size.width, height: max(0, size.height * base) + 4))
            for _ in 0..<count {
                let x = random.range(-0.05, 1.05) * size.width
                let h = size.height * height * random.range(0.7, 1.15)
                let w = h * random.range(0.28, 0.36)
                let foot = size.height * base
                let tiers = 4
                for tier in 0..<tiers {
                    let t = CGFloat(tier) / CGFloat(tiers)
                    let tierBase = foot + h * t * 0.78
                    let tierWidth = w * (1 - t * 0.62)
                    context.move(to: CGPoint(x: x - tierWidth / 2, y: tierBase))
                    context.addLine(to: CGPoint(x: x + tierWidth / 2, y: tierBase))
                    context.addLine(to: CGPoint(x: x, y: tierBase + h * (0.42 - t * 0.05)))
                    context.closePath()
                }
                // Fill the tiers before the trunk: a rect fill would
                // otherwise discard the pending path.
                context.fillPath()
                context.fill(CGRect(x: x - w * 0.04, y: foot - 2, width: w * 0.08, height: h * 0.2))
            }
            // Fog between layers.
            context.drawLinearGradient(
                fade(0xE9EDE4, from: 0, to: 0.28),
                start: CGPoint(x: 0, y: size.height * (base + height)),
                end: CGPoint(x: 0, y: size.height * base),
                options: [])
        }
        // A pale path winding toward the viewer.
        context.setFillColor(color(0xC9C1A7, 0.85))
        context.move(to: CGPoint(x: size.width * 0.47, y: size.height * 0.10))
        context.addCurve(
            to: CGPoint(x: size.width * 0.30, y: 0),
            control1: CGPoint(x: size.width * 0.40, y: size.height * 0.06),
            control2: CGPoint(x: size.width * 0.36, y: size.height * 0.03))
        context.addLine(to: CGPoint(x: size.width * 0.66, y: 0))
        context.addCurve(
            to: CGPoint(x: size.width * 0.50, y: size.height * 0.10),
            control1: CGPoint(x: size.width * 0.58, y: size.height * 0.03),
            control2: CGPoint(x: size.width * 0.52, y: size.height * 0.06))
        context.closePath()
        context.fillPath()
    }

    private static func drawStarryNight(_ context: CGContext, _ size: CGSize, _ random: inout Random) {
        sky(context, size, [(0x03050F, 0), (0x0B1636, 0.55), (0x1F2E5C, 0.85), (0x3B3F6E, 1)])
        // Milky Way: a diagonal haze of faint dots.
        for _ in 0..<2600 {
            let t = random.unit()
            let spread = random.range(-1, 1) * random.range(0, 1)
            let x = size.width * t
            let y = size.height * (0.25 + 0.7 * t) + spread * size.height * 0.16
            context.setFillColor(color(0xD9E2FF, random.range(0.02, 0.12)))
            let r = random.range(0.6, 2.4)
            context.fillEllipse(in: CGRect(x: x, y: y, width: r, height: r))
        }
        for _ in 0..<420 {
            let x = random.range(0, size.width)
            let y = random.range(size.height * 0.2, size.height)
            let r = random.unit() < 0.06 ? random.range(2.2, 3.4) : random.range(0.8, 1.8)
            context.setFillColor(color(0xFFFFFF, random.range(0.45, 1)))
            context.fillEllipse(in: CGRect(x: x, y: y, width: r, height: r))
        }
        context.setFillColor(color(0x05060C))
        context.addPath(ridge(size, base: size.height * 0.20, amplitude: size.height * 0.08, &random))
        context.fillPath()
        // A small warm tent glow on the ridge.
        let tent = CGPoint(x: size.width * 0.28, y: size.height * 0.16)
        glow(context, at: tent, radius: size.width * 0.06, color: 0xFFB45A, alpha: 0.65)
        context.setFillColor(color(0xFFC57A))
        context.move(to: CGPoint(x: tent.x - size.width * 0.018, y: tent.y - size.height * 0.012))
        context.addLine(to: CGPoint(x: tent.x + size.width * 0.018, y: tent.y - size.height * 0.012))
        context.addLine(to: CGPoint(x: tent.x, y: tent.y + size.height * 0.03))
        context.closePath()
        context.fillPath()
    }

    private static func drawSeaSunrise(_ context: CGContext, _ size: CGSize, _ random: inout Random) {
        let horizon = size.height * 0.40
        sky(context, size, [(0x2B4C7E, 0), (0x8E7FB0, 0.45), (0xF3A683, 0.85), (0xFAD7A0, 1)])
        let sun = CGPoint(x: size.width * 0.42, y: horizon + size.height * 0.07)
        glow(context, at: sun, radius: size.width * 0.35, color: 0xFFD49A, alpha: 0.7)
        context.setFillColor(color(0xFFF1D6))
        context.fillEllipse(in: CGRect(x: sun.x - size.width * 0.05, y: sun.y - size.width * 0.05,
                                       width: size.width * 0.1, height: size.width * 0.1))
        context.setFillColor(color(0x24385C))
        context.fill(CGRect(x: 0, y: 0, width: size.width, height: horizon))
        context.drawLinearGradient(
            gradient([(0x1A2944, 0), (0x5B6E96, 1)]),
            start: CGPoint(x: 0, y: 0), end: CGPoint(x: 0, y: horizon), options: [])
        // Sun path on the water.
        for _ in 0..<160 {
            let y = random.range(0, horizon * 0.98)
            let spread = (1 - y / horizon) * size.width * 0.16 + size.width * 0.02
            let x = sun.x + random.range(-spread, spread)
            let length = random.range(10, 60)
            context.setFillColor(color(0xFFE0B0, random.range(0.15, 0.6)))
            context.fill(CGRect(x: x - length / 2, y: y, width: length,
                                height: max(1.5, size.height * 0.003)))
        }
    }

    // MARK: - Avatars

    enum AvatarStyle {
        case scene(Scene, seed: UInt64)
        /// An SF Symbol, white, on a two-colour gradient.
        case glyph(String, top: UInt32, bottom: UInt32)
        /// Soft overlapping discs.
        case bubbles(UInt32, UInt32, UInt32, seed: UInt64)
    }

    static func avatar(_ style: AvatarStyle, side: Int = 256) -> CGImage? {
        switch style {
        case .scene(let scene, let seed):
            return landscape(scene, width: side, height: side, seed: seed)
        case .glyph(let symbol, let top, let bottom):
            return canvas(width: side, height: side) { context, size in
                context.drawLinearGradient(
                    gradient([(bottom, 0), (top, 1)]),
                    start: .zero, end: CGPoint(x: size.width * 0.3, y: size.height), options: [])
                withAppKit(context) {
                    let config = NSImage.SymbolConfiguration(
                        pointSize: size.width * 0.42, weight: .semibold)
                        .applying(.init(paletteColors: [.white]))
                    guard let image = NSImage(systemSymbolName: symbol, accessibilityDescription: nil)?
                        .withSymbolConfiguration(config) else { return }
                    let scale = size.width * 0.46 / max(image.size.width, image.size.height)
                    let w = image.size.width * scale, h = image.size.height * scale
                    image.draw(in: NSRect(x: (size.width - w) / 2, y: (size.height - h) / 2,
                                          width: w, height: h))
                }
            }
        case .bubbles(let a, let b, let c, let seed):
            return canvas(width: side, height: side) { context, size in
                var random = Random(seed: seed)
                context.setFillColor(color(a))
                context.fill(CGRect(origin: .zero, size: size))
                for (index, hex) in [b, c, b, c].enumerated() {
                    let r = size.width * random.range(0.35, 0.6)
                    let center = CGPoint(x: random.range(0, size.width), y: random.range(0, size.height))
                    context.setFillColor(color(hex, index < 2 ? 0.85 : 0.55))
                    context.fillEllipse(in: CGRect(x: center.x - r / 2, y: center.y - r / 2,
                                                   width: r, height: r))
                }
            }
        }
    }

    // MARK: - Sticker

    /// A big emoji with a white die-cut halo and a soft drop shadow, on a
    /// transparent canvas — how a sticker reads at a glance.
    static func sticker(_ emoji: String, side: Int = 512) -> CGImage? {
        canvas(width: side, height: side) { context, size in
            withAppKit(context) {
                let font = NSFont.systemFont(ofSize: size.width * 0.62)
                let text = NSAttributedString(string: emoji, attributes: [.font: font])
                let bounds = text.size()
                let origin = NSPoint(x: (size.width - bounds.width) / 2,
                                     y: (size.height - bounds.height) / 2 + size.height * 0.02)
                let halo = NSShadow()
                halo.shadowColor = .white
                halo.shadowBlurRadius = size.width * 0.012
                halo.shadowOffset = .zero
                // The halo: the glyph's own shape, stamped white around itself.
                for angle in stride(from: 0.0, to: Double.pi * 2, by: Double.pi / 8) {
                    NSGraphicsContext.saveGraphicsState()
                    halo.set()
                    let offset = size.width * 0.022
                    text.draw(at: NSPoint(x: origin.x + offset * cos(angle),
                                          y: origin.y + offset * sin(angle)))
                    NSGraphicsContext.restoreGraphicsState()
                }
                let shadow = NSShadow()
                shadow.shadowColor = NSColor.black.withAlphaComponent(0.35)
                shadow.shadowBlurRadius = size.width * 0.03
                shadow.shadowOffset = NSSize(width: 0, height: -size.width * 0.012)
                NSGraphicsContext.saveGraphicsState()
                shadow.set()
                text.draw(at: origin)
                NSGraphicsContext.restoreGraphicsState()
            }
        }
    }

    // MARK: - Voice

    /// Telegram's waveform format: 5-bit samples, packed MSB-first.
    static func packedWaveform(count: Int, seed: UInt64) -> Data {
        var random = Random(seed: seed)
        var bits: [UInt8] = []
        for index in 0..<count {
            let t = CGFloat(index) / CGFloat(count)
            // Speech-like: syllable bursts under a phrase envelope.
            let envelope = 0.35 + 0.65 * abs(sin(t * .pi * 3.2))
            let syllable = 0.4 + 0.6 * abs(sin(t * .pi * 23 + random.range(0, 0.8)))
            let value = Int((envelope * syllable * random.range(0.75, 1) * 31).rounded())
            let clamped = UInt8(max(1, min(31, value)))
            for shift in (0..<5).reversed() { bits.append((clamped >> UInt8(shift)) & 1) }
        }
        var bytes: [UInt8] = []
        var index = 0
        while index < bits.count {
            var byte: UInt8 = 0
            for offset in 0..<8 {
                byte <<= 1
                if index + offset < bits.count { byte |= bits[index + offset] }
            }
            bytes.append(byte)
            index += 8
        }
        return Data(bytes)
    }

    /// A short, quiet, mono WAV — something real on disk for the player to
    /// open, so the bubble shows its play state rather than a download arrow.
    static func writeVoiceClip(to url: URL, seconds: Int) -> Bool {
        let rate = 8000
        let count = rate * seconds
        var samples = [Int16](repeating: 0, count: count)
        for index in 0..<count {
            let t = Double(index) / Double(rate)
            let envelope = 0.5 + 0.5 * sin(t * 2 * .pi * 2.6)
            let value = sin(t * 2 * .pi * 220) * 0.6 + sin(t * 2 * .pi * 330) * 0.3
            samples[index] = Int16(value * envelope * 2600)
        }
        var data = Data()
        func append<T: FixedWidthInteger>(_ value: T) {
            withUnsafeBytes(of: value.littleEndian) { data.append(contentsOf: $0) }
        }
        let byteCount = count * 2
        data.append(contentsOf: Array("RIFF".utf8)); append(UInt32(36 + byteCount))
        data.append(contentsOf: Array("WAVE".utf8))
        data.append(contentsOf: Array("fmt ".utf8)); append(UInt32(16))
        append(UInt16(1)); append(UInt16(1)); append(UInt32(rate)); append(UInt32(rate * 2))
        append(UInt16(2)); append(UInt16(16))
        data.append(contentsOf: Array("data".utf8)); append(UInt32(byteCount))
        for sample in samples { append(sample) }
        return (try? data.write(to: url)) != nil
    }
}

#endif
