#!/usr/bin/env bash
# Generates Sources/TelegramCore/Secrets.generated.swift from .env.
#
# It lives in TelegramCore, not App, because the ITest `tool` target compiles
# Sources/TelegramCore + ITest and nothing from Sources/App — the headless
# test-DC harness needs the same api_id/api_hash the app does.
#
# This is the ONLY path by which TELEGRAM_API_ID / TELEGRAM_API_HASH reach the
# binary. Rules (docs/sessions/session-01-plan.md §3.8):
#   - never `set -x`, never echo a value — only its length;
#   - umask 077 so the generated file is not world-readable;
#   - write to a temp file and `cmp -s` before moving: rewriting identical
#     content still bumps mtime and forces a full module recompile.
set -euo pipefail
umask 077

script_dir="$(cd "$(dirname "$0")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"
env_file="$repo_root/.env"
out_file="$repo_root/Sources/TelegramCore/Secrets.generated.swift"

if [ ! -f "$env_file" ]; then
  echo "gen-secrets: $env_file missing — cp .env.example .env and fill it in" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a; . "$env_file"; set +a

api_id="${TELEGRAM_API_ID:-}"
api_hash="${TELEGRAM_API_HASH:-}"

if [ -z "$api_id" ] || [ -z "$api_hash" ]; then
  echo "gen-secrets: TELEGRAM_API_ID / TELEGRAM_API_HASH are empty in .env" >&2
  exit 1
fi

case "$api_id" in
  ''|*[!0-9]*) echo "gen-secrets: TELEGRAM_API_ID is not an integer" >&2; exit 1 ;;
esac

# Escape for a Swift string literal (backslash first, then quote).
esc_hash="${api_hash//\\/\\\\}"
esc_hash="${esc_hash//\"/\\\"}"

tmp_file="$(mktemp "${TMPDIR:-/tmp}/notchgram-secrets.XXXXXX")"
trap 'rm -f "$tmp_file"' EXIT

cat > "$tmp_file" <<SWIFT
// Generated by scripts/gen-secrets.sh — DO NOT EDIT, DO NOT COMMIT.
// Source: .env (gitignored). Contract: .env.example.

public enum Secrets {
    /// Telegram application api_id from my.telegram.org (app title "NotchGram").
    public static let telegramApiID: Int = $api_id
    /// Telegram application api_hash. Embedding it in the binary is normal and
    /// unavoidable — official clients ship theirs too. The rule is: never in
    /// git, never in logs.
    public static let telegramApiHash: String = "$esc_hash"
}
SWIFT

mkdir -p "$(dirname "$out_file")"
if cmp -s "$tmp_file" "$out_file" 2>/dev/null; then
  echo "gen-secrets: unchanged (api_id ${#api_id} digits, api_hash ${#api_hash} chars)"
else
  mv "$tmp_file" "$out_file"
  chmod 600 "$out_file"
  trap - EXIT
  echo "gen-secrets: wrote $out_file (api_id ${#api_id} digits, api_hash ${#api_hash} chars)"
fi
